blank_issues_enabled: false
contact_links:
  - name: Nous rejoindre sur Discord, pour toutes questions ou demandes
    url: https://discord.gg/2Zcjfykbcu
    about: Veuillez ouvrir les issues que pour signaler des bugs !
