# module du helios launcher
name: Launcher Build
on:
  push:
    branches: [ master ]

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 16
          
      - name: Check for update
        id: updatecheck
        uses: EndBug/version-check@v2
        with:
          diff-search: true

      - name: Set up Python
        if: steps.updatecheck.outputs.changed == 'true'
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Dependencies
        if: steps.updatecheck.outputs.changed == 'true'
        run: npm ci
        shell: bash

      - name: Build
        if: steps.updatecheck.outputs.changed == 'true'
        env:
          GH_TOKEN: ${{ secrets.github_token }}
        run: npm run build
        shell: bash
